import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tagoioSidebar: [
    {
      type: "autogenerated",
      dirName: "tagoio",
    },
  ],
  tagodeploySidebar: [
    "tagodeploy/",
    "tagodeploy/tago-deploy-enterprise-iot-platform-infrastructure",
    "tagodeploy/work-in-progress-tagodeploy-mqtt-broker-service",
  ],
  tagocoreSidebar: [
    {
      type: "autogenerated",
      dirName: "tagocore",
    },
  ],
};

export default sidebars;
