import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import apiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {
  tagoioSidebar: [
    {
      type: "autogenerated",
      dirName: "tagoio",
    },
  ],
  tagodeploySidebar: [
    {
      type: "autogenerated",
      dirName: "tagodeploy",
    },
  ],
  tagocoreSidebar: [
    {
      type: "autogenerated",
      dirName: "tagocore",
    },
  ],
  apiSidebar: apiSidebar,
};

export default sidebars;
