import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "index",
    {
      type: "category",
      label: "TagoIO Platform",
      collapsed: false,
      items: [
        "tagoio/index",
        "tagoio/getting-started",
        "tagoio/how-it-works",
        {
          type: "category",
          label: "Widgets",
          collapsed: true,
          items: [
            "tagoio/widgets/index",
            "tagoio/widgets/widgets-overview",
            "tagoio/widgets/widget-header",
            "tagoio/widgets/widget-cache-system",
            "tagoio/widgets/custom-widget",
            "tagoio/widgets/custom-widget-parameters",
            "tagoio/widgets/embedding-widgets-to-your-website",
            "tagoio/widgets/angular-widget",
            "tagoio/widgets/echarts-custom-widget-tutorial-",
            "tagoio/widgets/area-chart-widget",
            "tagoio/widgets/card-widget",
            "tagoio/widgets/clock-widget",
            "tagoio/widgets/compose-widget",
            "tagoio/widgets/cylinder-widget",
            "tagoio/widgets/device-list-widget",
            "tagoio/widgets/dial-widget",
            "tagoio/widgets/display-widget",
            "tagoio/widgets/dynamic-table-widget",
            "tagoio/widgets/entity-table-widget",
            "tagoio/widgets/grain-bin-widget",
            "tagoio/widgets/heat-map-widget",
            "tagoio/widgets/horizontal-bar-widget",
            "tagoio/widgets/icons-widget",
            "tagoio/widgets/image-marker-widget",
            "tagoio/widgets/image-widget",
            "tagoio/widgets/input-control-widget",
            "tagoio/widgets/input-form-widget",
            "tagoio/widgets/keypad-widget",
            "tagoio/widgets/creating-keypad-widgets",
            "tagoio/widgets/line-chart-widget",
            "tagoio/widgets/map-widget",
            "tagoio/widgets/geofences-in-map-widgets",
            "tagoio/widgets/multiple-axes-in-chart-widgets",
            "tagoio/widgets/multiple-charts-widget",
            "tagoio/widgets/note-widget",
            "tagoio/widgets/pie-widget",
            "tagoio/widgets/push-button-widget",
            "tagoio/widgets/semi-donut-widget",
            "tagoio/widgets/semi-pie-widget",
            "tagoio/widgets/solid-widget",
            "tagoio/widgets/static-table-widget",
            "tagoio/widgets/step-button-widget",
            "tagoio/widgets/tile-widget",
            "tagoio/widgets/user-list-widget-",
            "tagoio/widgets/vertical-column-widget",
            "tagoio/widgets/video-widget",
            "tagoio/widgets/vu-meter-widget",
          ],
        },
        {
          type: "category",
          label: "Dashboards",
          collapsed: true,
          items: [
            "tagoio/dashboards/index",
            "tagoio/dashboards/dashboard-overview",
            "tagoio/dashboards/blueprint-dashboard",
            "tagoio/dashboards/creating-dashboard-tabs",
            "tagoio/dashboards/dashboard-global-time-filter-and-period-presets",
            "tagoio/dashboards/dashboard-icons",
            "tagoio/dashboards/distributing-dashboards",
            "tagoio/dashboards/downlinks-using-dashboards",
            "tagoio/dashboards/grouping-dashboards",
            "tagoio/dashboards/restoring-your-dashboard-to-a-previous-version",
            "tagoio/dashboards/sharing-dashboards",
          ],
        },
        {
          type: "category",
          label: "Devices",
          collapsed: true,
          items: [
            "tagoio/devices/devices",
            "tagoio/devices/adding-devices-with-connectors",
            "tagoio/devices/blueprint-devices-entities",
            "tagoio/devices/configuration-parameters-for-devices",
            "tagoio/devices/device-data-management",
            "tagoio/devices/device-emulator",
            "tagoio/devices/device-emulator-functions",
            "tagoio/devices/device-token",
            "tagoio/devices/managing-devices",
            "tagoio/devices/radiobridge-devices",
            "tagoio/devices/sending-data-to-device",
            "tagoio/devices/using-the-device-emulator",
          ],
        },
        {
          type: "category",
          label: "Actions",
          collapsed: true,
          items: [
            "tagoio/actions/actions",
            "tagoio/actions/action-cron",
            "tagoio/actions/defining-actions",
            "tagoio/actions/running-analysis-via-action",
          ],
        },
        {
          type: "category",
          label: "Analysis",
          collapsed: true,
          items: [
            "tagoio/analysis/analysis-overview",
            "tagoio/analysis/analysis-service",
            "tagoio/analysis/creating-analysis",
            "tagoio/analysis/distributing-analysis",
            "tagoio/analysis/notifications-for-users-using-analysis",
            "tagoio/analysis/parser-vs-analysis-comparison",
            "tagoio/analysis/running-analysis-as-external-using-deno",
            "tagoio/analysis/running-analysis-as-external-using-nodejs",
          ],
        },
        {
          type: "category",
          label: "Data Management",
          collapsed: true,
          items: [
            "tagoio/data-management/index",
            "tagoio/data-management/chunk-management",
            "tagoio/data-management/data-analytics",
            "tagoio/data-management/data-export",
            "tagoio/data-management/data-records",
            "tagoio/data-management/data-retention-feature",
            "tagoio/data-management/deleting-data",
            "tagoio/data-management/filtered-variables",
            "tagoio/data-management/getting-data",
            "tagoio/data-management/grouping-variables",
            "tagoio/data-management/metadata",
            "tagoio/data-management/sending-data",
            "tagoio/data-management/tags-system",
          ],
        },
        {
          type: "category",
          label: "API & SDK",
          collapsed: true,
          items: [
            "tagoio/api/api-overview",
            "tagoio/api/restful-api",
            "tagoio/sdk/index",
            "tagoio/sdk/nodejs-sdk",
            "tagoio/sdk/python-sdk",
          ],
        },
        {
          type: "category",
          label: "Services",
          collapsed: true,
          items: [
            "tagoio/services/services-overview",
            "tagoio/services/allocating-services-to-profiles",
            "tagoio/services/data-input-service",
            "tagoio/services/data-output-for-dashboards",
            "tagoio/services/data-output-service",
            "tagoio/services/downgrading-plans-services",
            "tagoio/services/e-mail-service",
            "tagoio/services/end-users-service",
            "tagoio/services/file-storage-service",
            "tagoio/services/notification-service",
            "tagoio/services/pdf-service-generator",
            "tagoio/services/sms-service",
            "tagoio/services/upgrading-plans-services",
          ],
        },
        {
          type: "category",
          label: "Integrations",
          collapsed: true,
          items: [
            "tagoio/integrations/connector-overview",
            "tagoio/integrations/connecting-your-mqtt-broker-to-tagoio",
            "tagoio/integrations/creating-a-network-integration",
            "tagoio/integrations/network-integration",
            "tagoio/integrations/sharing-connectors-networks",
          ],
        },
        {
          type: "category",
          label: "Security & Access",
          collapsed: true,
          items: [
            "tagoio/security/index",
            "tagoio/security/access-management",
            "tagoio/security/audit-log",
            "tagoio/security/authorization",
            "tagoio/security/creating-a-policy",
            "tagoio/security/defining-permissions",
            "tagoio/security/security-and-compliance",
            "tagoio/security/single-sign-on-sso",
            "tagoio/security/two-factor-authentication-2fa",
          ],
        },
        {
          type: "category",
          label: "Entities",
          collapsed: true,
          items: ["tagoio/entities/entities"],
        },
        {
          type: "category",
          label: "Payload Parser",
          collapsed: true,
          items: [
            "tagoio/payload-parser/payload-parser",
            "tagoio/payload-parser/building-your-own-parser",
            "tagoio/payload-parser/filtering-out-variables-with-parser-code",
            "tagoio/payload-parser/payload-parser-context-global-variables",
            "tagoio/payload-parser/payload-parser-timeutils-library",
            "tagoio/payload-parser/payload-parser-troubleshooting",
            "tagoio/payload-parser/publishing-updating-and-accessing-decoders",
          ],
        },
        {
          type: "category",
          label: "Middleware",
          collapsed: true,
          items: ["tagoio/middleware/middleware"],
        },
        {
          type: "category",
          label: "Tutorials & Examples",
          collapsed: true,
          items: [
            "tagoio/tutorials/adeunis-with-lorawan",
            "tagoio/tutorials/adeunis-with-sigfox",
            "tagoio/tutorials/displaying-locations-on-a-map-with-ttn-lorawan",
            "tagoio/tutorials/downlink-for-lorawan",
            "tagoio/tutorials/everynet-lorawan",
            "tagoio/tutorials/lorawan-publication-of-environmental-measurements-with-a-lora-e5-module",
            "tagoio/tutorials/loriot-lorawan",
            "tagoio/tutorials/machineq-lorawan",
            "tagoio/tutorials/orbiwise-lorawan",
            "tagoio/tutorials/queclink-gps",
            "tagoio/tutorials/script-examples",
            "tagoio/tutorials/sensit-with-sigfox",
            "tagoio/tutorials/sigfox-downlink",
            "tagoio/tutorials/sigfox-using-advanced-data",
            "tagoio/tutorials/sigfox",
            "tagoio/tutorials/the-things-network-lorawan",
            "tagoio/tutorials/thinxtra-xkit-for-sigfox",
            "tagoio/tutorials/touchtag-lorawan-everynet",
          ],
        },
        {
          type: "category",
          label: "Account Management",
          collapsed: true,
          items: [
            "tagoio/account/account-token",
            "tagoio/account/deleting-your-account",
            "tagoio/account/editing-accounts-details",
            "tagoio/account/end-user-agreements",
            "tagoio/account/managing-your-account-with-the-tagoio-mobile-app",
            "tagoio/account/profiles",
            "tagoio/account/resetting-my-password",
            "tagoio/account/security-and-protection-for-run-users",
            "tagoio/account/team-management-sharing-your-profile",
            "tagoio/account/user-engagement",
            "tagoio/account/user-management",
          ],
        },
        {
          type: "category",
          label: "Billing",
          collapsed: true,
          items: [
            "tagoio/billing/account-plans",
            "tagoio/billing/billing-summary",
            "tagoio/billing/common-billing-issues",
            "tagoio/billing/refund-policy",
            "tagoio/billing/setup-billing",
          ],
        },
        {
          type: "category",
          label: "Notifications",
          collapsed: true,
          items: [
            "tagoio/notifications/notification",
            "tagoio/notifications/notifications-for-users",
            "tagoio/notifications/trigger-by-usage-alert",
          ],
        },
        {
          type: "category",
          label: "Other Topics",
          collapsed: true,
          items: [
            "tagoio/abs-telemetry",
            "tagoio/add-ons-overview",
            "tagoio/adding-image-selector-field-on-forms",
            "tagoio/beagle-bone-black",
            "tagoio/building-solutions",
            "tagoio/connecting-zen15-power-using-smartthings-hub",
            "tagoio/console-for-debug",
            "tagoio/control-tower",
            "tagoio/creating-a-sandbox",
            "tagoio/creating-dynamic-dropdown-selection-using-forms",
            "tagoio/custom-domain-configuration",
            "tagoio/custom-domain-whitelabel",
            "tagoio/custom-mobile-app",
            "tagoio/custom-settings",
            "tagoio/defining-targets",
            "tagoio/deploying-applications",
            "tagoio/dictionaries",
            "tagoio/displaying-units",
            "tagoio/environment-variables",
            "tagoio/field-types-for-input-form",
            "tagoio/files",
            "tagoio/form-fields-visibility",
            "tagoio/formula",
            "tagoio/frame-settings",
            "tagoio/gauge-data-range-format",
            "tagoio/gauge-overview",
            "tagoio/google-analytics",
            "tagoio/images-and-links-in-the-maps-pins",
            "tagoio/import-export-for-dictionary",
            "tagoio/keypad-data-manipulation",
            "tagoio/keypad-visualization",
            "tagoio/language-preferences",
            "tagoio/live-inspector",
            "tagoio/map-filters",
            "tagoio/map-layer-gis",
            "tagoio/markdown-guide",
            "tagoio/mqtt",
            "tagoio/mqtt-process-data-publish-it-and-subscribe-to-a-topic",
            "tagoio/mqtt-publishing-and-subscribing",
            "tagoio/mqtt-retain-on-tagoio-broker",
            "tagoio/mqtt-with-sensor-tag",
            "tagoio/navigation-bar",
            "tagoio/payment-methods",
            "tagoio/raspberry-pi",
            "tagoio/rate-limits-hard-limits",
            "tagoio/reference-lines",
            "tagoio/resource-limits",
            "tagoio/router",
            "tagoio/run-theme",
            "tagoio/script-editor",
            "tagoio/secrets",
            "tagoio/senet-network",
            "tagoio/senra-network",
            "tagoio/serial-number-format",
            "tagoio/sidebar",
            "tagoio/signup-fields",
            "tagoio/simulator-data-stream",
            "tagoio/tables",
            "tagoio/tagoio-mcp-ai-powered-iot-data-integration",
            "tagoio/ticket-severity-options",
            "tagoio/trigger-by-geofence",
            "tagoio/trigger-by-mqtt-topic",
            "tagoio/trigger-by-resource",
            "tagoio/trigger-by-schedule",
            "tagoio/trigger-by-variable",
            "tagoio/trigger-unlock",
            "tagoio/uploading-files",
            "tagoio/usage-policy",
            "tagoio/using-dictionaries-multi-language",
            "tagoio/zoho-salesiq",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "TagoRUN",
      collapsed: true,
      items: [
        "tagorun/index",
        "tagorun/branding-and-deploying-applications",
        "tagorun/run-module",
        "tagorun/tagorun-mobile-app",
      ],
    },
    {
      type: "category",
      label: "TagoDeploy",
      collapsed: true,
      items: [
        "tagodeploy/index",
        "tagodeploy/tago-deploy-enterprise-iot-platform-infrastructure",
        "tagodeploy/work-in-progress-tagodeploy-mqtt-broker-service",
      ],
    },
    {
      type: "category",
      label: "TagoCore",
      collapsed: true,
      items: [
        "tagocore/index",
        "tagocore/integration",
        "tagocore/tagocore-cluster",
        "tagocore/tagocore-open-source-documentation",
      ],
    },
  ],
};

export default sidebars;
