import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "category",
      label: "API Overview",
      collapsible: false,
      items: [
        {
          type: "doc",
          id: "api/tagoio-api",
          label: "Introduction",
        },
      ],
    },
    {
      type: "category",
      label: "Device Token (Device-level)",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Device Data",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/current-device-information",
              label: "Device Information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/get-data",
              label: "Get Data",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-data",
              label: "Edit Data",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/send-data",
              label: "Send Data",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/delete-data",
              label: "Delete Data",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "api/get-configuration-parameters",
              label: "List Config. parameters",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/mark-a-configuration-parameter-as-read",
              label: "Mark Config. Parameter as Read",
              className: "api-method put",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Network Token (Network-level)",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Network Ingest",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/get-device-token-with-serial-number-authorization",
              label: "Get Device-Token with Serial Number & Authorization Key",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/get-device-token-with-serial-number",
              label: "Get Device-Token with Serial Number",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-device-configuration-parameter",
              label: "Edit Device Configuration Parameter",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/send-data-using-network",
              label: "Send Data using Network",
              className: "api-method post",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Device Management",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Devices",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/list-of-devices",
              label: "List of Devices",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/create-new-device",
              label: "Create Device",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/device-information",
              label: "Device Information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-device",
              label: "Edit Device",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-device",
              label: "Delete Device",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "api/convert-device-type",
              label: "Convert Device Type",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/device-data-amount",
              label: "Device Data Amount",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/import-data-from-a-csv-in-files",
              label: "Import Data from a CSV in Files",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/empty-a-device-s-data",
              label: "Empty a Device's Data",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/get-device-data",
              label: "Get Device Data",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-device-data",
              label: "Edit Device Data",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-device-data",
              label: "Delete Device Data",
              className: "api-method delete",
            },
          ],
        },
        {
          type: "category",
          label: "Device Tokens",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/list-of-tokens",
              label: "List of Tokens",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/create-token",
              label: "Create Token",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/delete-token",
              label: "Delete Token",
              className: "api-method delete",
            },
          ],
        },
        {
          type: "category",
          label: "Mutable Device",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/export-data-to-csv-in-files",
              label: "Export data to CSV in Files",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Immutable Device",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/list-of-chunks",
              label: "List of Chunks",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/export-a-chunk-as-csv-to-files",
              label: "Export Chunk",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/delete-chunk",
              label: "Delete Chunk",
              className: "api-method delete",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Tago RUN",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Users",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/user-information",
              label: "User Information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-user",
              label: "Edit User",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-user",
              label: "Delete User",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "api/list-users",
              label: "List Users",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/create-user",
              label: "Create User",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Notifications",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/create-notification",
              label: "Create Notification",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/list-of-notifications",
              label: "List of Notifications",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-notification",
              label: "Edit Notification",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-notification",
              label: "Delete Notification",
              className: "api-method delete",
            },
          ],
        },
        {
          type: "category",
          label: "Dictionary",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/get-dictionary-list",
              label: "Get Dictionary List",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/create-dictionary",
              label: "Create Dictionary",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/get-dictionary-details",
              label: "Get Dictionary Details",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/update-dictionary",
              label: "Update Dictionary",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-dictionary",
              label: "Delete Dictionary",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "api/update-dictionary-language",
              label: "Update Dictionary Language",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/get-dictionary-language-details",
              label: "Get Dictionary Language Details",
              className: "api-method get",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Dashboards",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Dashboards",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/edit-dashboard",
              label: "Edit Dashboard",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-dashboard",
              label: "Delete Dashboard",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "api/list-dashboards",
              label: "List Dashboards",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/create-dashboard",
              label: "Create Dashboard",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/duplicate-dashboard",
              label: "Duplicate Dashboard",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/generate-public-token",
              label: "Generate Public Token",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/list-analysis-related-to-dashboard",
              label: "List Analysis related to Dashboard",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/list-devices-related-to-dashboard",
              label: "List Devices related to Dashboard",
              className: "api-method get",
            },
          ],
        },
        {
          type: "category",
          label: "Widgets",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/get-widget-information",
              label: "Get Widget Information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-widget",
              label: "Edit Widget",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-widget",
              label: "Delete Widget",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "api/get-widget-data",
              label: "Get Widget Data",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/create-dashboard-widget",
              label: "Create Widget",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/generate-token",
              label: "Generate Token",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/get-information",
              label: "Get Information",
              className: "api-method get",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "File(s) Management",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Files",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/get-profile-file-list",
              label: "Get Profile File List",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-a-file",
              label: "Move File",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/upload-file-part",
              label: "Upload File",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/delete-a-file",
              label: "Delete a File",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "api/edit-permission",
              label: "Edit Permission",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/file-copy",
              label: "File Copy",
              className: "api-method put",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Profile",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Statistics / Billing",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/get-the-account-plan",
              label: "Get the Account Plan",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/get-account-resources-allocation",
              label: "Get Account Resources Allocation",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/update-the-account-resources-allocation",
              label: "Update the Account Resources Allocation",
              className: "api-method post",
            },
          ],
        },
        {
          type: "category",
          label: "Account",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/login-to-account",
              label: "Login to Account",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/get-account-information",
              label: "Get Account Information",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-account",
              label: "Edit Account",
              className: "api-method put",
            },
          ],
        },
        {
          type: "category",
          label: "Profile",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/get-a-profile-statistics",
              label: "Get a Profile Statistics",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/get-a-profile-summary",
              label: "Get a Profile Summary",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/get-a-profile-details",
              label: "Get a Profile Details",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/generate-profile-token",
              label: "Generate Profile-Token",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/get-tags",
              label: "Get Tags",
              className: "api-method get",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Entities",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Entity",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/list-entities",
              label: "List Entities",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/create-entity",
              label: "Create Entity",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/get-entity-info",
              label: "Entity Info",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/update-entity",
              label: "Update Entity",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-entity",
              label: "Delete Entity",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "api/update-entity-schema",
              label: "Update Entity Schema",
              className: "api-method put",
            },
          ],
        },
        {
          type: "category",
          label: "Entity Data",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/get-entity-data-amount",
              label: "Get Entity Data Amount",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/get-entity-data",
              label: "Get Entity Data",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/edit-entity-data",
              label: "Edit Entity Data",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/add-entity-data",
              label: "Add Entity Data",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/delete-entity-data",
              label: "Delete Entity Data",
              className: "api-method delete",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Resources",
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Access Management",
          collapsible: false,
          className: "api-sub-category",
          items: [
            {
              type: "doc",
              id: "api/get-policy-list",
              label: "Get Policy List",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "api/create-policy",
              label: "Create Policy",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "api/update-policy",
              label: "Update Policy",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "api/delete-policy",
              label: "Delete Policy",
              className: "api-method delete",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
