import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/tagoio-api",
    },
    {
      type: "category",
      label: "Devices (With Device-Token)",
      items: [
        {
          type: "doc",
          id: "api/current-device-information",
          label: "Current Device Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-data",
          label: "Get data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/send-data",
          label: "Send data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/edit-data",
          label: "Edit data",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-data-only-for-mutable-device-type",
          label: "Delete data(Only for mutable device type)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-configuration-parameters",
          label: "Get configuration parameters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/mark-a-configuration-parameter-as-read",
          label: "Mark a configuration parameter as read",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Profile (With Profile-Token)",
      items: [
        {
          type: "doc",
          id: "api/list-of-tokens",
          label: "List of Tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-token",
          label: "Create token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-token",
          label: "Delete Token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-device-params",
          label: "List Device Params",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-and-edit-device-params",
          label: "Create and Edit Device Params",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-device-param",
          label: "Delete Device Param",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/create-new-device",
          label: "Create new Device",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-of-devices",
          label: "List of devices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/export-data-to-csv-in-files",
          label: "Export data to CSV in Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-of-chunks",
          label: "List of chunks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-a-buckets-chunk-retention",
          label: "Update a bucket's chunk retention",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/device-information",
          label: "Device information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-device",
          label: "Delete device",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/export-a-chunk-as-csv-to-files",
          label: "Export a chunk as CSV to Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-chunk",
          label: "Delete chunk",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/convert-device-type",
          label: "Convert Device Type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/device-data-amount",
          label: "Device data amount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/import-data-from-a-csv-in-files",
          label: "Import Data from a CSV in Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/empty-a-devices-bucket",
          label: "Empty a Device's Bucket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-device-data",
          label: "Get Device Data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-device-data-mutable-device-only",
          label: "Edit Device Data(mutable device only)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-device-data-mutable-device-only",
          label: "Delete Device Data(mutable device only)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/create-notification",
          label: "Create Notification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-of-notifications",
          label: "List of Notifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-notification",
          label: "Edit Notification",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-notification",
          label: "Delete Notification",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/user-information",
          label: "User Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-user",
          label: "Edit User",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-user",
          label: "Delete User",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-users",
          label: "List Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-user",
          label: "Create User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-run-settings",
          label: "Get RUN settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-settings",
          label: "Edit settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/login-as-user",
          label: "Login as User",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-entity",
          label: "Create Entity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-entities",
          label: "List Entities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-entity-info",
          label: "Get Entity Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-entity",
          label: "Update Entity",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-entity",
          label: "Delete Entity",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-entity-data-amount",
          label: "Get Entity Data Amount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-entity-schema",
          label: "Update Entity Schema",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/add-entity-data",
          label: "Add Entity Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-entity-data",
          label: "Get Entity Data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-entity-data",
          label: "Edit Entity Data",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-entity-data",
          label: "Delete Entity Data",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-of-buckets",
          label: "List of Buckets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/bucket-information",
          label: "Bucket Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/bucket-data-amount",
          label: "Bucket Data Amount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-widget-information",
          label: "Get Widget Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-widget",
          label: "Edit Widget",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-widget",
          label: "Delete Widget",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-widget-data",
          label: "Get Widget Data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-dashboard-widget",
          label: "Create Dashboard Widget",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-token",
          label: "Generate Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-information",
          label: "Get Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-dashboard",
          label: "Edit Dashboard",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-dashboard",
          label: "Delete Dashboard",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-dashboards",
          label: "List Dashboards",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-dashboard",
          label: "Create Dashboard",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/duplicate-dashboard",
          label: "Duplicate dashboard",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-public-token",
          label: "Generate Public Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-analysis-related-to-dashboard",
          label: "List Analysis related to Dashboard",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-devices-related-to-dashboard",
          label: "List Devices related to Dashboard",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/upload-file-part-1",
          label: "Upload file part 1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-profile-file-list",
          label: "Get profile file list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-a-file",
          label: "Edit a file",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-file",
          label: "Delete a file",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/edit-permission",
          label: "Edit Permission",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/file-copy",
          label: "File Copy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-the-account-plan",
          label: "Get the Account Plan",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-account-resources-allocation",
          label: "Get account resources allocation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-the-account-resources-allocation",
          label: "Update the account resources allocation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/login-to-account",
          label: "Login to Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-account-information",
          label: "Get Account Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-account",
          label: "Edit Account",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/create-policy-target-user",
          label: "Create Policy -  Target User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-policy-list",
          label: "Get Policy List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-policy",
          label: "Update policy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-policy",
          label: "Delete Policy",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-a-profile-statistics",
          label: "Get a Profile Statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-a-profile-summary",
          label: "Get a Profile Summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-a-profile-details",
          label: "Get a Profile Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-dictionary-list",
          label: "Get Dictionary List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-dictionary",
          label: "Create Dictionary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dictionary-details",
          label: "Get Dictionary Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-dictionary",
          label: "Update Dictionary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-dictionary",
          label: "Delete Dictionary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/update-dictionary-language",
          label: "Update Dictionary Language",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-dictionary-language-details",
          label: "Get Dictionary Language Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/generate-profile-token",
          label: "Generate Profile-Token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-tags",
          label: "Get Tags",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Devices",
      items: [
        {
          type: "doc",
          id: "api/list-of-tokens",
          label: "List of Tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-token",
          label: "Create token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-token",
          label: "Delete Token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-device-params",
          label: "List Device Params",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-and-edit-device-params",
          label: "Create and Edit Device Params",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-device-param",
          label: "Delete Device Param",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/create-new-device",
          label: "Create new Device",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-of-devices",
          label: "List of devices",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/export-data-to-csv-in-files",
          label: "Export data to CSV in Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-of-chunks",
          label: "List of chunks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-a-buckets-chunk-retention",
          label: "Update a bucket's chunk retention",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/device-information",
          label: "Device information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-device",
          label: "Delete device",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/export-a-chunk-as-csv-to-files",
          label: "Export a chunk as CSV to Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-chunk",
          label: "Delete chunk",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/convert-device-type",
          label: "Convert Device Type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/device-data-amount",
          label: "Device data amount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/import-data-from-a-csv-in-files",
          label: "Import Data from a CSV in Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/empty-a-devices-bucket",
          label: "Empty a Device's Bucket",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-device-data",
          label: "Get Device Data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-device-data-mutable-device-only",
          label: "Edit Device Data(mutable device only)",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-device-data-mutable-device-only",
          label: "Delete Device Data(mutable device only)",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Token",
      items: [
        {
          type: "doc",
          id: "api/list-of-tokens",
          label: "List of Tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-token",
          label: "Create token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-token",
          label: "Delete Token",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Configuration Param",
      items: [
        {
          type: "doc",
          id: "api/list-device-params",
          label: "List Device Params",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-and-edit-device-params",
          label: "Create and Edit Device Params",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-device-param",
          label: "Delete Device Param",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Mutable Device",
      items: [
        {
          type: "doc",
          id: "api/create-new-device",
          label: "Create new Device",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/export-data-to-csv-in-files",
          label: "Export data to CSV in Files",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Immutable Device",
      items: [
        {
          type: "doc",
          id: "api/list-of-chunks",
          label: "List of chunks",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-a-buckets-chunk-retention",
          label: "Update a bucket's chunk retention",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/export-a-chunk-as-csv-to-files",
          label: "Export a chunk as CSV to Files",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-chunk",
          label: "Delete chunk",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Tago RUN",
      items: [
        {
          type: "doc",
          id: "api/create-notification",
          label: "Create Notification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-of-notifications",
          label: "List of Notifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-notification",
          label: "Edit Notification",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-notification",
          label: "Delete Notification",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/user-information",
          label: "User Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-user",
          label: "Edit User",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-user",
          label: "Delete User",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-users",
          label: "List Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-user",
          label: "Create User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-run-settings",
          label: "Get RUN settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-settings",
          label: "Edit settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/login-as-user",
          label: "Login as User",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      items: [
        {
          type: "doc",
          id: "api/create-notification",
          label: "Create Notification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-of-notifications",
          label: "List of Notifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-notification",
          label: "Edit Notification",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-notification",
          label: "Delete Notification",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/user-information",
          label: "User Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-user",
          label: "Edit User",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-user",
          label: "Delete User",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-users",
          label: "List Users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-user",
          label: "Create User",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Notification",
      items: [
        {
          type: "doc",
          id: "api/create-notification",
          label: "Create Notification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-of-notifications",
          label: "List of Notifications",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-notification",
          label: "Edit Notification",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-notification",
          label: "Delete Notification",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Entity",
      items: [
        {
          type: "doc",
          id: "api/create-entity",
          label: "Create Entity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-entities",
          label: "List Entities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-entity-info",
          label: "Get Entity Info",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-entity",
          label: "Update Entity",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-entity",
          label: "Delete Entity",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-entity-data-amount",
          label: "Get Entity Data Amount",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-entity-schema",
          label: "Update Entity Schema",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/add-entity-data",
          label: "Add Entity Data",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-entity-data",
          label: "Get Entity Data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-entity-data",
          label: "Edit Entity Data",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-entity-data",
          label: "Delete Entity Data",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Buckets",
      items: [
        {
          type: "doc",
          id: "api/list-of-buckets",
          label: "List of Buckets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/bucket-information",
          label: "Bucket Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/bucket-data-amount",
          label: "Bucket Data Amount",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Dashboards",
      items: [
        {
          type: "doc",
          id: "api/get-widget-information",
          label: "Get Widget Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-widget",
          label: "Edit Widget",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-widget",
          label: "Delete Widget",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-widget-data",
          label: "Get Widget Data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-dashboard-widget",
          label: "Create Dashboard Widget",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-token",
          label: "Generate Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-information",
          label: "Get Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-dashboard",
          label: "Edit Dashboard",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-dashboard",
          label: "Delete Dashboard",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/list-dashboards",
          label: "List Dashboards",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-dashboard",
          label: "Create Dashboard",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/duplicate-dashboard",
          label: "Duplicate dashboard",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-public-token",
          label: "Generate Public Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-analysis-related-to-dashboard",
          label: "List Analysis related to Dashboard",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/list-devices-related-to-dashboard",
          label: "List Devices related to Dashboard",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Widgets",
      items: [
        {
          type: "doc",
          id: "api/get-widget-information",
          label: "Get Widget Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-widget",
          label: "Edit Widget",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-widget",
          label: "Delete Widget",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-widget-data",
          label: "Get Widget Data",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-dashboard-widget",
          label: "Create Dashboard Widget",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/generate-token",
          label: "Generate Token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-information",
          label: "Get Information",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Files",
      items: [
        {
          type: "doc",
          id: "api/upload-file-part-1",
          label: "Upload file part 1",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-profile-file-list",
          label: "Get profile file list",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-a-file",
          label: "Edit a file",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-a-file",
          label: "Delete a file",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/edit-permission",
          label: "Edit Permission",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/file-copy",
          label: "File Copy",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Upload",
      items: [
        {
          type: "doc",
          id: "api/upload-file-part-1",
          label: "Upload file part 1",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Statistics / Billing",
      items: [
        {
          type: "doc",
          id: "api/get-the-account-plan",
          label: "Get the Account Plan",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-account-resources-allocation",
          label: "Get account resources allocation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-the-account-resources-allocation",
          label: "Update the account resources allocation",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Account",
      items: [
        {
          type: "doc",
          id: "api/login-to-account",
          label: "Login to Account",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-account-information",
          label: "Get Account Information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-account",
          label: "Edit Account",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Access Management",
      items: [
        {
          type: "doc",
          id: "api/create-policy-target-user",
          label: "Create Policy -  Target User",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-policy-list",
          label: "Get Policy List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-policy",
          label: "Update policy",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-policy",
          label: "Delete Policy",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Profile",
      items: [
        {
          type: "doc",
          id: "api/get-a-profile-statistics",
          label: "Get a Profile Statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-a-profile-summary",
          label: "Get a Profile Summary",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-a-profile-details",
          label: "Get a Profile Details",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Dictionary",
      items: [
        {
          type: "doc",
          id: "api/get-dictionary-list",
          label: "Get Dictionary List",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-dictionary",
          label: "Create Dictionary",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-dictionary-details",
          label: "Get Dictionary Details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-dictionary",
          label: "Update Dictionary",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-dictionary",
          label: "Delete Dictionary",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/update-dictionary-language",
          label: "Update Dictionary Language",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-dictionary-language-details",
          label: "Get Dictionary Language Details",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Network (With Network-Token)",
      items: [
        {
          type: "doc",
          id: "api/get-device-token-with-serial-number-authorization",
          label: "Get Device-Token with Serial Number & Authorization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-device-token-with-serial-number",
          label: "Get Device-Token with Serial Number",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/edit-device-configuration-parameter",
          label: "Edit Device Configuration Parameter",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/send-data-using-network",
          label: "Send Data using Network",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
